// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbsepgecpdznuisjlhoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZic2VwZ2VjcGR6bnVpc2psaG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzc4NTYsImV4cCI6MjA2MjkxMzg1Nn0.t-OLkvuyGgz2c0xIhmjrhXaC_zdU2fKhnL_29d6eBkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);